### ISSUE TITLE
期末考试

### ISSUE THREAD

**Issue by SFUMECJF** [Theigrams/Mathematical-optimization#1]
您好前辈，期末考试怎么复习鸭。

**Comment by Theigrams** [comment]
> 您好前辈，期末考试怎么复习鸭。

年代太久远，已经忘了。。。

**Comment by SFUMECJF** [comment]
> > 您好前辈，期末考试怎么复习鸭。
> 
> 年代太久远，已经忘了。。。

哈哈。谢谢。过了。75分

**Comment by Theigrams** [comment]
> > > 您好前辈，期末考试怎么复习鸭。
> > 
> > 
> > 年代太久远，已经忘了。。。
> 
> 哈哈。谢谢。过了。75分

挺好的，我也才八十多😭
